version: '3.8'

services:
  # PHP сервис
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pdf_form_app
    restart: unless-stopped
    working_dir: /var/www/
    ports:
      - "8888:8000"
    volumes:
      - ./:/var/www
    networks:
      - pdf_form_network
    command: bash -c "
      chown -R dev:www-data storage bootstrap/cache &&
      chmod -R 775 storage bootstrap/cache &&
      php artisan config:clear &&
      php artisan serve --host=0.0.0.0 --port=8000"
    depends_on:
      - db

  # MySQL сервис
  db:
    image: mysql:8.0
    container_name: pdf_form_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - pdf_form_network

  # phpMyAdmin сервис
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pdf_form_phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8889:80"
    networks:
      - pdf_form_network
    depends_on:
      - db

networks:
  pdf_form_network:
    driver: bridge 